create table if not exists public.users (
    id bigint generated by default as identity primary key,
    user_name text not null check (char_length(trim(user_name)) between 1 and 100),
    country text not null check (char_length(trim(country)) between 1 and 100),
    position text not null check (char_length(trim(position)) between 1 and 100),
    salary numeric not null check (salary >= 0 and salary <= 10000000),
    department text not null check (char_length(trim(department)) between 1 and 100),
    years_of_service integer not null check (years_of_service >= 0 and years_of_service <= 80),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;

create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

create index if not exists users_user_name_idx on public.users (user_name);
create index if not exists users_country_idx on public.users (country);
create index if not exists users_department_idx on public.users (department);
